#!/bin/sh
LOG_FILE=/apps/logs/nginx.log
echo "Log Location: [ $LOG_FILE ]"

start_nginx() {
  echo "Starting nginx server..."
  nginx
  echo "Starting php-fpm server..."
  php-fpm 
}

copy_resourcesFile 2>&1 | tee -i $LOG_FILE
start_nginx  2>&1 | tee -i $LOG_FILE
